---
title             : "Sociotechnical energy imaginaries of non-users of ECO-innovations: identification and perceptions of residential households not adopting solar energy"
shorttitle        : "Sociotechnical energy imaginaries of non-users"
date              : "`r Sys.Date()`"

author: 
  - name          : "Marco Bunt"
    affiliation   : "1,2"
    corresponding : yes    # Define only one corresponding author
    address       : "Stedin, Blaak 8, 3011 TA Rotterdam"
    email         : "marco.bunt@Stedin.net"
 

affiliation:
  - id            : "1"
    institution   : "Erasmus school of social and behavioral sciences"
  - id            : "2"
    institution   : "Stedin netbeheer"


authornote:
  This article is the graduation thesis of Marco Bunt in the Department of public administration and sociology at the Erasmus school of social and behavioral sciences, in collaboration with Stedin.

abstract:
  In the effort of the Dutch government to transition houses to sustainable (decentralized) ways of energy, everyone is expected to participate. In order to make the energy-transition inclusive for all societal groups, this thesis investigates imaginaries of people that are not participating in the adaptation of solar panels (PV). Although non-adopters are typically perceived as uneducated and reluctant to change, they can have real reasons for not adopting (Rogers, 1983). By examining the sociotechnical energy imaginaries and the sociotechnical imaginaries of the people in this group, this thesis seeks to understand why some people are not adopting sustainable technologies. The examination of the imaginaries is done via a process of interviewing non-adaptors and analyzing the transcripts. In this thesis, it is argued that adopting PV is not only a matter of having the material resources to purchase the technological equipment, but that it is also a matter of having the conviction that sustainable energy is a necessity for the future. Although there is research focused on people that are adopting, not a lot is understood about the motivations of people who are not transitioning their houses to sustainable energy. This thesis seeks to fill that gap. The literature for (Levy and Spices, 2013) is applied as a basis for sociotechnical energy imaginaries, e.g., climate apocalypse imaginary of fossil fuels forever.  This thesis consists of two parts. The first part is a quantitative analysis of factors predicting adaptation of PV via an analysis of the geographical locations of PV on the part of the Dutch energy grid. From the data, peer-influence appeared to be the most useful prediction for the adoption of PV and is used to identify the non-users of PV. The second part is a qualitative part, were semi-structured interviews are conducted to gain insight in reasoning for non-adapting and the role of imaginaries in the decision-making process. People who lived in houses that were exposed to PV by their surrounding neighbors but ho nevertheless adopted PV were approached for the interviews. Via this process, three imaginaries of non-adaptors are identified: 1) collective action imaginary. Respondents that expressed this imaginary, described that action to improve the climate was a necessity but expected the government to arrange a collective effort via (very clear) subsidies or regulations. 2) Systemic change imaginary. Respondents made statements like _"climate change is done by big companies"_. Due to the external cause of climate change, respondents did not take individual action. 3) (Temporary) crisis imaginary. Respondents that hold this imaginary see the climate on earth as resilient and imagine that there is time to wait for fore better solutions before solving the climate issue. Together these imaginaries withheld people from taking measures to prevent human-induced climate change.
  
  
keywords          : "Sociotechnical energy imaginaries, ECO-innovation,  diffusion of innovation, non-users"
wordcount         : "9931"

bibliography      : ["r-references.bib"]

#class: doc,11pt#, twoside
floatsintext      : yes
figurelist        : yes
tablelist         : yes
footnotelist      : no
linenumbers       : no
linkcolor         : "blue"
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf # Use papaja::apa6_docx for Word documents #apa6_pdf
---

```{r setup, include = FALSE}
source('./funct/Basics.R')

ipak(c("papaja", "remedy", "kableExtra", "dplyr", "tidyr", "knitr", "kableExtra", "ggplot2"))
options(knitr.kable.NA = '')
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r child = './chpt/Introduction.Rmd'}
```

```{r child = './chpt/Problem.Rmd'}
```

```{r child = './chpt/Theoretical_framework.Rmd'}
```

```{r child = './chpt/Study1.Rmd'}
```

```{r child = './chpt/Study2.Rmd'}
```

```{r child = './chpt/GereralConclu.Rmd'}
```

```{r child = './chpt/GereralDiscus.Rmd'}
```


```{r child = './chpt/Appendix_1.Rmd'}
```


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")

```


\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup

```{r child = './chpt/ETHICAL.Rmd'}
```

