# General discussion
In this mixed-method study, non-adapters have a high potential for being able to adopt (see results or the regression, table \@ref(tab:regressie)) but are nevertheless not adopting new ECO-innovations. The results show that the respondents in this thesis that did not adopt, have a high possibility of not adopting in the future, if the Dutch government does not take action on (one of ) of thee aspects. 1) the perception of "crisis" needs to change via e.g., campaigns of the government want people to invest in unprofitable ECO-innovation. For some people, if they do not see the climate issue as urgent, they will not invest without the expectation of profit. Otherwise, they wait until a better moment of option comes to adopt. 2) the government needs to ensure the effort of working towards a sustainable environment is a collective one. Some people are willing to invest in a sustainable climate without the expectation of a return of investment, as long as the investment is done by everyone. As a prisoner dilemma, the possibility of others profiting from their investment keeps them from investing. 3) the effect/necessity of private investments need to be legitimized. Some people see the climate issue as a problem created by the capitalistic system, not by individual action. This view hinders them from making a costly investment.

The findings of this thesis are limited to people that do have the resources to adopt ECO-innovation but are not adopting. This thesis does not contain information on how people who do not have the resources necessary to adopt ECO-innovation view the climate crisis. It would be interesting to investigate how people from this group see the challenge for a sustainable environment. Another limitation of this study is the missing of useful information about the resources (e.g., income or price of the house) of the respondents. The interviews were unannounced, most of them were in the doorway of the house. This environment maybe was not comfortable enough for respondents to talk about financial struggles. A study that would merely focus on the role of natural resources in the process of not-adopting would create a better insight. However, since both the study's in this thesis concluded that the role of, e.g., a higher annual income does not necessarily lead to a higher change of adopting, we feel confident to say that social-technical energy imaginaries play a significant role in the process of (not) adopting sustainable technology. 

## Personal reflection
The insight into the role of imaginaries in the process of (not) adopting new technology is new for me as a researcher. I usually work as a data scientist trying to make predictions based on data. Personally, I do not believe that a problem that is created by assets can be eliminated by creating more assets.  Think that the imaginary of the climate crisis is pragmatic since this is only a focus on the carbon that we are emitting. By solving the climate crisis via ECO-innovation, new problems like trade wars over rare-earth materials. During the interviews for this thesis, I became more aware that, due to the way we imagine climate change as the rising of the level of carbon in the atmosphere, we are missing the bigger problem of overconsumption. This shows how we shape our environment via the way we imagine it ought to be. During the interviews in this thesis, my natural response to incorrect argument of a responded would be to counter it with good statistics and it was sometimes a struggle to only listen. During the thesis, I learned that a good understanding of the imaginary of how we think it ought to be might be just as important as good statistics.