# Introduction
<!-- _"For whoever has will be given more, and they will have an abundance. Whoever does not have, even what they have will be taken from them."_ Matthew 25:29. Although the words are primary about divine discipleship, it is also a principle in the natural world: people that have the upper hand gain advantages to further increase their lead [@merton_1968; @gladwell_2013]. One of the places where this effect is visible, is in the adaptation of new technologies. 
#More educated people are the first to take advantage of new technological advances [@rogers_1983], and thereby improve their position in relative comparison to the people that are unable to adopt. This article is about the identification of people that are not adopting innovations that prevent climate change, and understanding why they are nog adopting.-->  
<!-- Wat -->In the process of modernization, unsustainability is produced as a side-effect of economic and technological development [@ipcc_2014]. The unsustainability becomes visible in the over-consumption of natural resources, loss of biodiversity and climate change problems. To overcome these problems, climate change urges national and local governments to make policies to enable energy transition from fossil energy sources that are free from emitting carbon in the atmosphere. The Dutch government aims to reduce the emission of carbon by 50% or more before 2030. <!--Evidently, this effect is happening in the transition to (more) sustainable sources of energy.--> 
One of the challenges in this vision <!--for a carbon- neutral environment-->is the transformation of more than 7 million houses, mostly moderately insulated and almost all heated by natural gas, to well-insulated houses, headed with energy from a sustainable source and in which clean electricity is used [@klimaat_2019, p. 21]. This goal means an extensive and expansive transformation of the Dutch society where everyone has to participate. The technology used for achieving this goal is mainly decentralized power generation through photovoltaic solar panels (PV), windmills and heat pumps (HP). Fossil-based transport shall be replaced by electric vehicles (EV), either with batteries or hydrogen [@klimaat_2019]. Technology’s like these that enable a more sustainable way of living will be called “ECO-innovations” [@James_1997] in this article, as described in the theoretical framework of this article.
<!-- The Matthew effect again becomes visible through the way the Dutch government uses a neoliberal marked principles to push energy transition:-->

These new technologies are more likely to be adopted by people that have more [@rogers_1983], and thereby improve their position in relative comparison to the people that are unable to adopt[@merton_1968; @gladwell_2013]. Thereby people that can innovate can sustain their lifestyle as consumers while lowering their environmental impact with the help of government subsidies, while people that are not adopting the new technology can only create a sustainable lifestyle by consuming less [@jhagroe_2015]. In this way, Jhagroe argues that the transitions increase the already existing gap between rich and poor [-@jhagroe_2015]. 
<!-- Waarom --><!-- Wetenschappelijke rekevantie -->A large amount of research is devoted to identifying innovators in general [@bogers_2010] and innovators of sustainable technology such as PV [@vasseur_kemp_2015]. 
However, there is not much theory (that we know of) about the people who are not transitioning themselves to sustainable forms of energy. Therefore academic research on this topic is needed. 
<!-- Maatschappelijke rekevantie -->Late adopters of an innovation are most likely to be individually blamed for not adopting an innovation or for being much later in adopting than the other members of their system, while careful analysis can show that an innovation maybe is not appropriate for this group [@rogers_1983]. Therefore it is important to study the people that are not adopting sustainable innovations in the present-day energy transition, to prevent stigmatization for this group. In understanding why the group is not adopting this, this article gains social relevance.
<!-- Hoe -->This article studies the people that are not adopting ECO-innovations by conducting a mixed-method inquiry, including a quantitative part to identify the non-adopters, and a qualitative part to understand  why they are not adopting. The former part is done via a multivariate regression analysis on the spatial diffusion of PV to find parameters predicting people not adopting. The latter part is done by conducting semi-structured interviews with people from the identified groups.
