# Part 2: Understanding non-adoptors \label{Study2}
Although @rogers_1983  defines non-adopters of innovation typically as low educated and reluctant to change, Rogers also argues that this group can have real reasons for not adopting. This part of the thesis investigates the arguments of the non-adopters as identified (and localized) in part \hyperref[Study1]{part one} of this study by interviewing people from this group. In this part of the study, people that are identified as having the resources to adopt ECO-innovation, but are however not adopting the innovation, are selected for interviewing participants about their views on the future energy system and the role of ECO-innovation in that perception on the future of energy. These interviews are analyzed to find emerging patterns in the normative frameworks from this group. To gain more information about the process of innovating to ECE-innovation, interviews were also conducted with people that did purchase PV. Together, the interviews with both the adopters and non-adopters helped to create a better understanding of energy imaginaries that people can have.

##Method
### Participants. 
Participants in this part of the study are people who are, based on material resources, able to adopt PV but are nevertheless not adopting ECO-innovation. The parameters do to this selection are provided by part one of this study. The results of the regression [table \@ref(tab:regressie)] indicate that home ownership, availability of PV, and low residential movement correlates with the adoption of PV. Based on these parameters, two neighborhoods are selected to conduct interviews. In total, 13 people were interviewed, varying in time from 5 minutes to 1 hour. Some were conducted while standing in the doorway at the entrance of the house; other interviews were held inside of the house, depending on the hospitality of the household.

### Procedure. 
The selection of the participants within the selected area's was made via non-probability convenience sampling [@creswell_poth_2018 ]. This way of sampling is because it enabled the interviewers to make the decision where to interview, based on the availability of people in the chosen area, at the time when the interviews were conducted. The interviews took place on weekday day during the day.
The interviews were semi-structured. By asking things like how they view the relative advantage of the technique, and the complexity of the system, we tried to understand the participants view on their attributes towards ECO-innovation [@rogers_1983]. To investigate the sociotechnical energy imaginaries, the interview focused on the way the participants view the stability of the ecosystem and how the view change on a global scale [@levy_spicer_2013]. The transcripts of the interviews are analyzed using Atlas.ti, Excel, and mind mapping techniques. 

## Validity and reliability  
A critical process of reflection guarantees the validity of the qualitative part of the research. For example, the analyzes of the interviews were peer-evaluated by another the researcher. Explicit inclusion and exclusion criteria have been drawn up for applying the codes, with which a high degree of inter-coder reliability is observed (Creswell & Poth, 2018; Neuman, 2014). By using the different methods, the general validity of the research is guaranteed by methodical triangulation (Neuman, 2014). Findings in this part of the study were matched with part one of the study.  However, it is important to point out that the external validity of the study is limited because it examines a fairly select target group. The availability of respondents, based on convenience, has a possible bias. Interviews were conducted during working hours. People that were at were a job were not able to respond. Although some of the respondents had a job but were nevertheless at home due to parenting or because they were working at home, we did not encounter, e.g., people that work five days a week at the office. The results are possibly biased by that fact the respondents were sampled at the same time, and not on different time frames. The conclusions of the study cannot, therefore, be generalized by definition. The findings are limited to the respondents in this part of the study. The relatively small research group enables us to go into depth during the interviews to complement part one of this thesis.

## Results. 
In the interviews conducted amongst non-users, none of the respondents suggested that financing the panels was an issue that prevents them from buying PV. This finding corresponds with the finding in part one of this study, that shows that the income of a household does not predict the adoption of PV on a continuous scale, but is more likely to function as an enabler to buy the technology. The respondents explained that they would be able to buy PV, but expressed other, diverse, reasons for not adopting the technology. In this result section of the second part of this thesis, first the contextual parameters are elaborated, after that the future energy imaginaries from the respondents that are not-adopting ECO-innovations are elaborated.

### Future energy imaginaries of non-adopters
This thesis investigates the future energy imaginaries of the non-adopters of ECO-innovation. From the interviews amongst people that did not adopt installed PV, three imaginaries for a sustainable future are identified, namely: collective action, systemic change, and (temporary) crisis. 

#### Imagining collective action
In the transition to a sustainable landscape, the Dutch government uses subsidies to persuade citizens to adopt the new technology. This does not necessarily fit with the vision of some of the respondents in this inquiry since they expressed what seemed to be a desire for collective action, controlled by the government. The innovators in the diffusion of innovation are willing to take the risk of making a bad investment; other groups are more reluctant toward change and less willing to take this risk [@rogers_1983 ]. Respondents that did not adopt PV expressed that the uncertainty regarding the payback period of the investment. One respondent 5 stated: "it's uncertain how long the regulations of energy purchasing (salderingsregeling) will continue. If the government decides to dismiss the current regulations, it will take a minimum of 20 years to recoup my investment." Respondents who were vocal about their desire for the government to provide insurance about their investment in the transition to sustainable technologies seemed to want the government to take collective action to improve the sustainability of their circumstances. A common argument, used by many of the respondents, was "my share is just a drop in the ocean" ( "een drupel op een gloeiende plaat"). Most of the respondents that expressed this feeling told that only collective effort would solve the problem and desired (or demanded) that the government come up with a set of economically viable measures. Hobbes [@hobbes_shapiro_2010] demonstrate that individuals, despite being rational actors, are unable to arrange and keep cooperative agreements without enforcement by the state. The respondents experience the struggle for sustainability as a prisoners dilemma, where people are willing to give up resources if everyone else in society does this as well. A sovereign government with absolute regulations for sustainability is security that others will not gain by their effort. The respondents express this in statements like " the government is talking a lot, but not taking measures. They ought to come up with solutions". This statement opposes the neo-liberal solution the Dutch government uses to cope with the climate crisis, as described in the previous section. The unwillingness of taking the risk of making an expensive investment while others continue to consume cheap (unsustainable) energy, restrain people in this group from purchasing PV.

Another uncertainty that respondents expressed was that they did not know for how long they will continue living in the house. One respondent stated:  "This house has lots of stairs. Now the going up and down goes well, but we're old, so we're not sure for how long we will stay here. Therefore we're not buying panels. It can take ten years for the investment to pay back, that is too long." (respondent 2)  Respondents thought PV would be not a good investment since it is unsure if the investment will turn a profit when they sell the house. When asked how they envision the future of the climate, these respondents expressed concern about the future of the climate. They were, however, rely upon on the government to create regulation that creates a sustainable future. They did not express a personal responsibility for sustainable lifestyles. This again is evidence for the prisoner's dilemma in sustainability. Government subsidy regulations enforce this dilemma. One respondent explained: 
"If I had been faster to buy PV, I could have benefitted from the available subsidies. These days the subsidies are less lucrative." (respondent 5) 
Although the price of PV has decreased dramatically in the last decade [@the_economist_2012], the respondent had the feeling he was missing out on the governmental contribution to his sustainable innovation. Hobbes's argument for absolutism will solve the problem of the individual desire to profit from the global crisis. The Dutch government uses neo-liberal marked principles to push innovation towards a sustainable future. Via this marked, innovation is stimulated, but also inequality in produced. Exactly the risk of investing in sustainable innovations create the possibility for individuals to gain financially, and to lose. Respondents were expressing that the fear of making an unprofitable investment made them relucted to invest. That is: not if not everyone is doing it. This asks questions about the scale of the climate crisis. Some respondents (that adopted PV), expressed that they, as individuals like to live a sustainable lifestyle, while others that did not adopt PV expressed that they expect the government to take measures. People from the latter group seemed to expect that the government will take care of the well-being of the citizens, based on equal opportunities and equal distribution of wealth. This suggests that people who are more in favor of a well-fare state form of government are less likely to take individual measures to engage in a market-driven effort to a sustainable lifestyle. In this way, the image that citizens have of ideal government control influences their sustainable practices.

#### Imagining systemic change
For an individual effort of citizens to adopt ECO-innovation, people need to feel responsible for the problem on an individual level. Some of the respondents in this thesis expressed that they did not feel individually responsible for climate change since, in their vision, others responsible for the effect human activity has on the climate. The climate crisis is in their view a result of a non-functioning system, and thereby, they are saying (not explicitly) that the crisis is a result of capitalism. A respondent questioned if, a problem created by technology can be solved by technology. When asked if he thought that ECO-innovation could fix the climate crisis, replied:

Most of the panels are produced in China. Due to work, I come there often, and I think it is questionable to participate in business with that regime. Also, for the production of PV, we need to use lots of materials. That is still wrong, so I'm not sure if panels and windmills are going to fix the problem. (respondent 5)

When respondents were asked if they feel responsible for the problems in the present climate on earth, some respondents expressed that they perceived the climate problem as a problem of big companies. They did not feel like they are not responsible for the massive production of $CO_{\text{2}}$, but that this problem is created by a small group of big companies emitting large quantities of $CO_{\text{2}}$. @moore_2015 conceptualizes this as the problem of accumulation of capital via the exploitation of cheap nature. As a result of the human activity on earth, the current era is conceptualized as the Anthropocene. In this depiction of the climate problem, climate change is the result of the Anthropocene, in which human influence on the planet is so profound that it will leave its legacy for millennia [@Macfarlane_2016]. In the klimaatakkoord [@klimaat_2019], the temperature on earth ought to be reversed to a pre-industrial era. This pre-industrial era refers to the period of several centuries prior to the start of the large-scale industrial activity around 1750, measured as the Global mean surface temperature [GMST; @ipcc_2014]. Using this starting point of reference for the measurements, the scale of measuring climate change includes that climate change originates in the industrial age. 
By imagining climate change as the consequences of an Anthropocene era, the problem is portrayed as to which everyone contributes and thereby, everyone has to participate in reducing the impact that human life has on the earth temperature. In this way, a public is created for the klimaatakkoord [-@klimaat_2019] and the corresponding set of measures to prevent human-induced climate change. @moore_2015 shows that climate change is not necessarily a problem of industrialization, but primarily a problem of capitalism. Capitalism not only exploits labor, but it also appropriates nature. According to @moore_2015, the strive for economic progress, through the exploitation of man and nature, the capitalist system is the engine behind climate change, and industrialization is only a consequence of this. The capitalist framework within climate change takes place remains invisible in the klimaatakkoord [-@klimaat_2019] by depicting climate change as a problem of the Anthropocene. This is stated in the klimaatakkoord as the following:

We staan aan de vooravond van een grote verbouwing. Een transformatie van onze ruim 7 miljoen huizen en 1 miljoen gebouwen, veelal matig geïsoleerd en vrijwel allemaal verwarmd door aardgas, tot goed geïsoleerde woningen en gebouwen, die we met duurzame warmte verwarmen en waarin we schone elektriciteit gebruiken of zelfs zelf opwekken. Klimaatverandering is een belangrijke reden voor deze verbouwing. Maar er is meer. We willen immers zo snel mogelijk kunnen stoppen met de aardgaswinning in Groningen. En we hebben allemaal wel behoefte aan een minder hoge energierekening en een comfortabeler woning. [@klimaat_2019, p 21]

We are on the eve of a large scale renovation of the Dutch society. A transformation of our more than 7 million houses and 1 million buildings, mostly moderately insulated and almost all heated by natural gas, into well-insulated homes and buildings that we heat with sustainable heat and in which we use clean electricity or even generate it ourselves. Climate change is an important reason for this renovation. Also, there is more. After all, we want to be able to stop the extraction of natural gas in Groningen as quickly as possible. And we all need a lower energy bill and a more comfortable home.  [@klimaat_2019, p 21]

By depicting sustainability as is done in the klimaatakkoord [-@klimaat_2019], the environment is "made more sustainable": the energy demand of society may remain, but without the emission of $CO_{\text{2}}$. The climate agreement creates the opportunity to imagine a future in which everyone lives in a clean (in terms of energy) and comfortable (in terms of temperature) home. Because the current housing stock "is mostly moderately insulated and almost all are heated by natural gas," the climate agreement justifies a large-scale renovation of the homes in the Netherlands. Houses with a gas connection are unsustainable, and houses with (as an example) a heat pump are sustainable. The interviews show that respondents depict the climate issue in another way, not as a problem of the anthropo (human), but as a problem of capitalism. The respondents that expressed that they did, although they communicated their concern for the climate, not feel responsible for climate change in a personal way. In their opinion, climate issues are created by large companies, and thereby the obligation to find suitable solutions for the problem ought, from there perspective, also come from these companies. From this perspective, the ecological crisis is not an external crisis. From a Capitalocene perspective, it is an internal crisis, caused by the way we as humans live together. Over the last decades, labor, food, energy, and raw materials were cheap [@moore_2015 ]. With the collapse of the ecosystem, this has come to an end. Respondents that expressed that they do not feel responsible for the crisis, because they blame others (commercial) parties for the damage done to the ecosystem. Because they see imagine the crisis caused by a neo-liberal system, they do not feel part of the cause of the problem and thereby also not a part of the solution. For them, the problem is in the means of production.

#### Imagining a (temporary) crisis
One of the most interesting encounters during the interviews was with a man who initially offered to help me find my way around the neighborhood. When asked about his perception, the man expressed the concern he had for leaving a liveable planet for his grandchildren. As we went further in the conversation about the climate issue and the possibility of adopting a more sustainable lifestyle, the man said: 
"it is weird, isn't it, that I do have concerns about the future of the climate, but I'm not doing anything to change it. I do want to leave a good planet for my grand-children" (respondent 13)
He emphasized that he tried to take measures for insulating his house, but when that seemed to be infeasible, he stopped the effort. The man repeatedly stated, as being hit by his the contradictory within this own behavior, "it is strange, isn't it?". Latour convincingly writes about this problem of "madness" [@latour_2017]. He writes: 

Talking about a crisis would be just another way of reassuring ourselves, saying that this too will pass, the crisis will soon be behind us. If only it were just a crisis! If only it had been just a crisis! [...] According to the experts, all of us are affected, on the inside, in the intimacy of our precious little existences, by these news bulletins that warn us directly about what we ought to eat and drink, about our land use, our modes of transportation, our clothing choices. As we hear one piece of bad news after another, you might expect us to feel that we had shifted from a mere ecological crisis into what should instead be called a profound mutation in our relation to the world. And yet this is surely not the case. For we receive all this news with astonishing calm, even with an admirable form of stoicism. If a radical mutation were really at issue, we would all have already modified the bases of our existence from top to bottom. We would have begun to change our food, our habitats, our means of transportation, our cultural technologies, in short, our mode of production. [...] We might even be taking our grandchildren to visit museums devoted to this struggle, hoping that they would be as stunned by our progress as they are today when they see how the Second World War gave rise to the Manhattan Project, the refinement of penicillin, and the dramatic progress of radar and air travel " [@latour_2017, p. 21].

This attitudes towards climate was expressed during another encounter.  When a respondent was asked about his perceptions on the resilience of the climate on earth (for "resilience," see \hyperref[TheoImag]{theory section}), the respondent stated: 
"some years ago, we had the problem that there was a hole in the ozone layer. now we have a new problem that is $CO_{\text{2}}$. I'm sure that the earth will correct itself. I don't know how, but I'm sure it will" (respondent 6). 
The respondent referred to the climate as a stable object, that had the ability to correct itself. This perception on the climate as "stable," is opposed to how a stable climate is theorized by @lovelock_2014, who argues that a stable climate is a dead climate since a chemical unbalance is the premise for life on earth. Respondents that imagined the climate crisis as a temporary issue, without the risk of extinction of human life, see the stability as something that will guarantee the possibility of life on earth. In their perception, the earth is stable enough to cope with the problems that human life is creating for the climate. Looking at the climate issue as a (temporary) crisis implies that it is only a matter of time until a proper solution is found. The climate crisis is imagined as a crisis like a war is a crisis; we need to wait until it is over. When the climate issue is envisioned as a temporary and fixable problem, there is time to wait and find more proper measures. Respondents expressed their desire for better, more advanced ECO-innovation and also expressed a willingness to wait for this invention to happen. Thereby the climate crisis imaginary prevented respondents from adopting ECO-innovations.

### Stimulating factors for transformation
The interviews also provide insight into factors contributing to a successful transformation to ECO-innovation. As suggested in the theoretical framework of this thesis, peer-influence appeared to influence the adoption process indeed. In the social influence debate, there are two forms of influence; 'herd behavior' (imitations of others) and for 'social learning' (learning via network) [@salazar_2012]. This thesis finds evidence for a social learning process that invigorates local communities. Hert-behavior is challenging to detect [@schultz_2008], in this thesis, there was no evidence found of neighbors mimicking behavior. The following section explains the process of social learning and how it shapes transitions.

#### Invigorating local communities
The interviews show that adoption is not only influenced by future energy imaginaries, but by a variety of other factors. One of these factors is the way respondents imagine their local community. The local community serves as the basis for peer-influence, and help dealing with uncertainty in a variety of forms.  When respondents were asked: "If you would like to purchase PV, would you know how to do it?", some respondents answered that they are uncertain about how to do it. The difficulty for them was not direct in the purchase itself, but in the part that comes after the purchase, e.g., in accessing subsidies or getting the panels on the roof. Respondents thought that there would be subsidies available for them, but they did not know how to access them. For some respondents, also the installation of the panels itself was problematic. One respondent answered: 

"I don't know how to arrange the generated electricity with my VVE (owners association), and how am I supposed to get the cable from the rooftop the fuse box? The roof is collective property. If we buy the panels together, I don't know how to divide the yield of the panels amongst the houses. If my fridge is on at the time there is energy from the panels, how do we deal with that financially?" (respondent 1).

Some of the respondents described how they tried to search for information on the internet, but that all the different information they encountered prevent them from continuing to explore the possibilities. The uncertainty kept them from buying PV. This uncertainty could explain why there is a peer-effect in the adoption of PV, as described in the first part of this study since people can learn from each other how to overcome these difficulties. Another finding that suggests the existence of a peer-influence is that almost all of the respondents who did purchase PV told that neighbors contacted them in the past for information about the purchase. One respondent narrated: "I've had people that I did not even know coming to my door, asking me how they could also buy and install these sole panels" (respondent 4). The contact that neighbors have with each other concerning PV indicates a social learning mechanism as theorized by [@nolan_2008], where the available knowledge in the network is used to gain knowledge to adopt ECO-innovation. It also corresponds with the notion of "Observability," as defined by @rogers_1983. The first adoption of PV in a neighborhood network is thereby essential in the transformation of an area to sustainable sources of energy. Other respondents expressed concerns about the visual aspect of the panels on the roof. One respondent explicitly stated: "I don't like these panels on the roof, I think it is ugly. Al long as others (neighbors) are not buying them (PV-panels), will also not do it. If someone in the steeds does is, then everyone can do just as well" (respondent 11). This indicates that some people are afraid of a negative social effect to buy PV. This is lifted after the first person installed PV on the roof. This (again) suggests that there is a neighborhood effect in the adoption of PV via social learning.

The peer-effect in the adoption of PV suggests that innovation neighborhoods to sustainable energy is not only a matter of constructing new, physical, infrastructure to generate carbon-free energy. With the adoption of PV by one member of a community, nonphysical networks are formed om people interested in innovating. In these networks, the panels on houses are a way of communicating the possibility of transitioning to a sustainable future. Together with the technical functions of the panels, the panels also hold ethnographical aspects by influencing (local) attitudes and knowledge about sustainability [@star_1999]. The installation of PV is a way for the innovation to enter the public sphere, where people discuss and imagine a sustainable society[@habermasn_2015, @warner_2014]. These publics form a civil society, where voluntary associations between members lead to a collective adoption of the new technology. Within this discourse, subaltern publics are unable to participate in the conversation [@fraser_1990]. While intervening, also respondents that rented the house they occupied were encountered. One respondent explained: "We rent this house. I would like it to be more sustainable, but it is up the owner of the house to install the panels. It would be even greater if by energy bill could also drop, I would like that to happen" (respondent 3). This example explains how not everyone can actively participate in the public discussion of transforming the Dutch landscape to$CO_{\text{2}}$ neutral sources. The public for the @klimaat_2019 consist only of businesses and homeowners (both private and corporate), tenants are excluded from the conversation. Social learning is delimited to people who can participate in the public for sustainable innovation. Thereby, the neo-liberal activities exclude a large population of society from participating in the struggle for sustainability.

## Discussion
Building from the findings of @levy_spicer_2013, the expectation was to find that some of the respondents would hold an apocalyptic view of the future of the climate on earth. Although this image is widely spread via platforms like Netflix, none of the respondents communicated a view that correlates with this view. The opposite seemed accurate: they depicted the issue as a temporary crisis. It is, however, a possibility that respondents did have apocalyptic views on the climate, but that there were other reasons why they did not communicate it. Therefore, this thesis does not conclude that the climate-apocalypse is not valid, only that we were not able to identify it. There is a possibility that the respondents imagined the world coming to an end, but did not communicate it, due to other reasons. For a following study, it would be interesting to focus on the people that hold an apocalyptic view. Since these people are fully convinced about the impact of human life on earth on the climate, it is interesting to investigate if people from this group adopt ECO-innovations. The interviews show how the inmaginaries of respondents shaped their behavior and thereby shaping the (sustainable) future [@jasanoff_kim_2015]. 